In [ ]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Datasheet.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Alex Mason' 123.0 35.0]
 ['Woods' 100.0 25.0]
 ['Ghost' 90.0 27.0]
 ['Kyle Rlley' 90.0 32.0]
 ['Woods' 40.0 nan]
 ['Alex Winston' 10.0 30.0]
 ['Ghost' nan 30.0]
 ['McMillan' 200.0 47.0]
 ['Trevor Noah' 30.0 21.0]
 ['Hudson' 40.0 40.0]]


In [ ]:
print(y)

['Active' 'Active' 'KIA' 'KIA' 'KIA' 'Active' 'Active' 'Active' 'Active'
 'Active']


In [ ]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(x[:, 1:3])
x[:, 1:3] = impute.transform(x[:, 1:3])

In [ ]:
print(x)

[['Alex Mason' 123.0 35.0]
 ['Woods' 100.0 25.0]
 ['Ghost' 90.0 27.0]
 ['Kyle Rlley' 90.0 32.0]
 ['Woods' 40.0 31.88888888888889]
 ['Alex Winston' 10.0 30.0]
 ['Ghost' 80.33333333333333 30.0]
 ['McMillan' 200.0 47.0]
 ['Trevor Noah' 30.0 21.0]
 ['Hudson' 40.0 40.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 123.0 35.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 100.0 25.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 90.0 27.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 90.0 32.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 31.88888888888889]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 10.0 30.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 80.33333333333333 30.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 200.0 47.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 30.0 21.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 40.0 40.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 1 1 1 0 0 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 80.33333333333333 30.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 31.88888888888889]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 123.0 35.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 90.0 32.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 100.0 25.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 200.0 47.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 30.0 21.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 10.0 30.0]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 90.0 27.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 40.0 40.0]]


In [ ]:
print(y_train)

[0 1 0 1 0 0 0 0]


In [ ]:
print(y_test)

[1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.5773502691896258 -0.06775087456345437
  -0.2076144031037063]
 [0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 1.7320508075688774 -0.7806079025789316
  0.05626932420567753]
 [1.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.5773502691896258 0.686345816229778
  0.49090134565642723]
 [0.0 0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272
  -0.3779644730092272 -0.5773502691896258 0.10309915694438739
  0.07179189640034711]
 [0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 1.7320508075688774 0.2798405688490512
  -0.9061301518638398]
 [0.0 0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903
  -0.3779644730092272 -0.5773502691896258 2.047254687895689
  2.167339142680748]
 [0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  2.6457513110645903 -0.5773502691896258 -0.9573493144835954
  -1.4649427508719468]
 [0.0 1.0 

In [ ]:
print(x_test)

[[0.0 0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.5773502691896258 0.10309915694438739
  -0.6267238523597864]
 [0.0 0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.5773502691896258 -0.7806079025789316
  1.1894170944165607]]
